[versions]
kotlin = "2.2.0"
shadow = "8.3.6"
proguard = "7.7.0"
cereal = "1.7.1"
kotlinx-coroutines = "1.7.3"
mockk = "1.14.2"

[libraries]
cereal-sdk = { module = "com.cereal-automation:cereal-sdk", version.ref = "cereal" }
cereal-licensing = { module = "com.cereal-automation:cereal-licensing", version.ref = "cereal" }
cereal-test-utils = { module = "com.cereal-automation:cereal-test-utils", version.ref = "cereal" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
